////////////////////////////////////////////////////////////////////////////////
//
// ADOBE SYSTEMS INCORPORATED
// Copyright 2007-2010 Adobe Systems Incorporated
// All Rights Reserved.
//
// NOTICE:  Adobe permits you to use, modify, and distribute this file 
// in accordance with the terms of the license agreement accompanying it.
//
////////////////////////////////////////////////////////////////////////////////
package flashx.textLayout.compose
{
	/** A Slug is geomtrical line information, generated by a Parcel. It has data required for composition. */
	[ExcludeClass]
	public class Slug
	{
		public var leftMargin:Number;
		public var rightMargin:Number;
		public var width:Number;	// logical width
		public var depth:Number;
		public var height:Number;	// logical height
		public var wrapsKnockOut:Boolean;	// true if the slug is narrow because it encountered a knockout (e.g., for a float)
	}
}
